name: Build and Upload Plugin ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Plugin Directory
        run: |
          mkdir iqbible-advanced-study-bible-wordpress-plugin
          shopt -s extglob
          mv !(iqbible-advanced-study-bible-wordpress-plugin|.git|.github) iqbible-advanced-study-bible-wordpress-plugin/

      - name: Zip Plugin Folder
        run: zip -r IQBiblePlugin.zip iqbible-advanced-study-bible-wordpress-plugin

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: IQBiblePlugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
