<!-- Notes -->

<?php // Prevent direct access
if (!defined('ABSPATH')) {
    exit;
} ?>
 
<h2><?php esc_html_e( 'My Notes', 'iqbible' ); ?></h2>
<div class="iqbible-notes-container">
    <?php if ( is_user_logged_in() ) : ?>
        <div class="iqbible-notes-editor">
            <?php
            $content   = ''; // Initialize with empty content or preloaded note content if needed.
            $editor_id = 'iqbible_editor'; // Unique ID for the TinyMCE editor.
            $settings  = array(
                'media_buttons' => false,
                'textarea_name' => 'iqbible_editor', // Matches the name attribute for the textarea generated by wp_editor
                'textarea_rows' => 15, // Reduced rows slightly for typical layout
                'teeny'         => true, // Use the simple TinyMCE config
                'quicktags'     => false, // Disable the HTML quicktags bar
            );
            wp_editor( $content, $editor_id, $settings );
            ?>
            <div class="iqbible-note-buttons">
                <?php // Use esc_attr_e for 'value' or data attributes, esc_html_e for visible text content ?>
                <button id="save-note-btn"><?php esc_html_e( 'Save New Note', 'iqbible' ); ?></button>
                <button id="cancel-note-btn" style="display: none;"><?php esc_html_e( 'Cancel', 'iqbible' ); ?></button>
                <input type="hidden" id="iqbible-editing-note-id" value=""> <?php // Hidden field to store ID when editing ?>
            </div>
        </div>

        <div id="saved-notes">
            <h3><?php esc_html_e( 'Your Saved Notes', 'iqbible' ); ?></h3>
            <div id="iqbible-notes-list">
                <!-- Notes will be loaded dynamically using AJAX -->
                <p><?php esc_html_e( 'Loading your saved notes...', 'iqbible' ); // Optional loading message ?></p>
            </div>
        </div>
    <?php else :
        // Include the already internationalized logged-out message
        include( 'logged-out.php' );
    endif; // End is_user_logged_in()
    ?>
</div>