name: Release Plugin

on:
  release:
    types: [published] # This workflow will run when a new release is published

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN for uploading release assets
    env:
      PLUGIN_DIR: iqbible-advanced-study-bible-wordpress-plugin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release zip
        run: |
          # Create zip directly in the current directory
          zip -r "${{ env.PLUGIN_DIR }}.zip" . \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/*" \
            -x "src/*" \
            -x "composer.json" \
            -x "composer.lock" \
            -x "Gruntfile.js" \
            -x "webpack.config.js" \
            -x "package.json" \
            -x "package-lock.json" \
            -x "README.md" \
            -x "create-release-zip.sh"
          
          echo "Created release zip: ${{ env.PLUGIN_DIR }}.zip"
          ls -lh "${{ env.PLUGIN_DIR }}.zip"

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.PLUGIN_DIR }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}